languageCode = "en-us"
title = "Eduardo Duarte"
baseurl = "https://edduarte.com"
googleAnalytics = "UA-103779128-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    blog = "/:slug/"
    talk = "/:slug/"
    paper = "/:slug/"

[params]
    description = "Junior Software Developer. Philonoist, over-thinker, cinephile and music junkie."
