languageCode = "en-us"
languageLang = "en"
title = "Ed Duarte"
baseurl = "https://www.edduarte.com"
enableGitInfo = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
disableKinds = ["tags", "categories"]
enableRobotsTXT = true
disableAliases = true
PygmentsCodeFences = true
PygmentsStyle = "solarizedlight"

[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

[mediaTypes."text/netlify"]
suffixes = []
delimiter = ""

[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[taxonomies]
  category = ""
  tags = ""

[permalinks]
  essays = "/:title/"
  projects = "/:title/"
  papers = "/:title/"
  talks = "/:title/"
