languageCode = "en-us"
languageLang = "en"
title = "Eduardo Duarte"
baseurl = "https://www.edduarte.com"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
disableKinds = ["tags", "categories"]
enableRobotsTXT = true
disableAliases = false

[outputs]
home = ["HTML", "RSS", "REDIRECTS"]

[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[taxonomies]
  category = ""
  tags = ""

[permalinks]
    essays = "/:title/"
    projects = "/:title/"
    papers = "/:title/"
