languageCode = "en-us"
languageLang = "en"
title = "Ed Duarte"
baseurl = "https://www.edduarte.com/"
enableGitInfo = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
disableKinds = ["categories"]
enableRobotsTXT = true
disableAliases = true
pygmentsUseClassic=true
PygmentsCodeFences = true
PygmentsStyle = "solarizeddark"

[Params]
cacheBuster = "13"

[author]
name = "Ed Duarte"
email = "hi@edduarte.com"

[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

[mediaTypes."text/netlify"]
suffixes = []
delimiter = ""

[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[taxonomies]
  tag = "tags"
  type = "types"
  series = "series"
  subsection = "subsections"

[permalinks]
  tags = "/:slug/"
  types = "/:slug/"
  series = "/:slug/"
  posts = "/:slug/"

[related]
includeNewer = true

[[related.indices]]
name = "parents"
weight = 1

[[related.indices]]
name = "id"
weight = 1
