languageCode = "en"
title = "Eduardo Duarte"
baseurl = "https://www.edduarte.com"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
disableKinds = ["tags", "categories"]

[outputs]
home = ["HTML", "RSS"]

[taxonomies]
  category = ""
  tags = ""

[permalinks]
    essay = "/:slug/"
    project = "/:slug/"
    paper = "/:slug/"
